### ISSUE TITLE
CreateVolumes should return a message if there is a volume name collision

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#10]
Currently, there is just no reply:

```
[mulhern@dhcp-25-209 stratis-cli]$ PYTHONPATH=./src ./bin/stratis logical create deadpool oubliette
Namespace(func=<function create_volumes at 0x7f10beeae410>, pool='deadpool', subparser_name='create', volume=['oubliette'])


[mulhern@dhcp-25-209 stratis-cli]$ PYTHONPATH=./src ./bin/stratis logical create deadpool oubliette
Namespace(func=<function create_volumes at 0x7fcb09f2d410>, pool='deadpool', subparser_name='create', volume=['oubliette'])


Traceback (most recent call last):
  File "./bin/stratis", line 39, in <module>
    main()
  File "./bin/stratis", line 36, in main
    return next(execution)
  File "/home/mulhern/my-projects/stratis-cli/src/stratis_cli/_main.py", line 41, in run
    raise err
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

This is due to a seg fault, rather than normal execution. It fails to return a message because it crashes.

**Comment by trgill** [comment]
just pushed a fix for this...

**Comment by mulkieran** [comment]
This can be closed now.
