### ISSUE TITLE
Test failures on loop_test_add_datadevs and loop_test_filesystem_snapshot

### ISSUE THREAD

**Issue by bgurney-rh** [stratis-storage/stratisd#1667]
I tried a test-loop run of the stratisd tests (loop devices, since there were no test devices defined), and I see the following test failures:

(stratisd repo has the HEAD revision eb01704ddb9bf)

```
test engine::strat_engine::pool::tests::loop_test_add_datadevs ... ERROR 2019-10-21T16:48:37Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool read only! -> ReadOnly
FAILED
```
```
test engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot ... FAILED
```

Output excerpt (part of a "runalltests.sh" test run):
```
running 27 tests
test engine::strat_engine::backstore::backstore::tests::loop_test_add_cache_devs ... ok
test engine::strat_engine::backstore::backstore::tests::loop_test_request ... ok
test engine::strat_engine::backstore::backstore::tests::loop_test_setup ... ok
test engine::strat_engine::backstore::blockdevmgr::tests::loop_test_blockdevmgr_used ... ok
test engine::strat_engine::backstore::blockdevmgr::tests::loop_test_fail_single_signature ... ok
test engine::strat_engine::backstore::blockdevmgr::tests::loop_test_initialization_stratis ... ok
test engine::strat_engine::backstore::blockdevmgr::tests::loop_test_initialize ... ok
test engine::strat_engine::backstore::blockdevmgr::tests::loop_test_ownership ... ok
test engine::strat_engine::backstore::cache_tier::tests::loop_cache_test_add ... ok
test engine::strat_engine::backstore::data_tier::tests::loop_test_add_and_alloc ... ok
test engine::strat_engine::backstore::device::test::loop_test_device_empty ... ok
test engine::strat_engine::backstore::device::test::loop_test_device_other_ownership ... ok
test engine::strat_engine::engine::test::loop_test_pool_rename ... ok
test engine::strat_engine::engine::test::loop_test_setup ... ok
test engine::strat_engine::pool::tests::loop_test_add_cachedevs ... ok
test engine::strat_engine::pool::tests::loop_test_add_datadevs ... ERROR 2019-10-21T16:48:37Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool read only! -> ReadOnly
FAILED
test engine::strat_engine::pool::tests::loop_test_basic_metadata ... ok
test engine::strat_engine::pool::tests::loop_test_empty_pool ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_rename ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot ... FAILED
test engine::strat_engine::thinpool::thinpool::tests::loop_test_full_pool ... ERROR 2019-10-21T16:48:47Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool out of space! -> OutOfSpace
ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_greedy_allocation ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_pool_setup ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_set_device ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_suspend_resume ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_thindev_destroy ... ok
test engine::strat_engine::thinpool::thinpool::tests::loop_test_thindev_expand ... ok

failures:

---- engine::strat_engine::pool::tests::loop_test_add_datadevs stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 5, kind: Other, message: "Input/output error" })', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12: libstratis::engine::strat_engine::pool::tests::test_add_datadevs
             at src/engine/strat_engine/pool.rs:768
  13: core::ops::function::Fn::call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:69
  14: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec::{{closure}}
             at src/engine/strat_engine/tests/loopbacked.rs:112
  15: std::panicking::try::do_call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  19: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec
             at src/engine/strat_engine/tests/loopbacked.rs:111
  20: libstratis::engine::strat_engine::pool::tests::loop_test_add_datadevs
             at src/engine/strat_engine/pool.rs:777
  21: libstratis::engine::strat_engine::pool::tests::loop_test_add_datadevs::{{closure}}
             at src/engine/strat_engine/pool.rs:776
  22: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  27: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
  28: test::run_test::run_test_inner
             at src/libtest/lib.rs:1488
  29: test::run_test
             at src/libtest/lib.rs:1507
  30: test::run_tests
             at src/libtest/lib.rs:1166
  31: test::run_tests_console
             at src/libtest/lib.rs:971
  32: test::test_main
             at src/libtest/lib.rs:292
  33: test::test_main_static
             at src/libtest/lib.rs:326
  34: libstratis::main
  35: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  36: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  37: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  38: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  39: std::panicking::try
             at src/libstd/panicking.rs:275
  40: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  41: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  42: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  43: main
  44: __libc_start_main
  45: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec
             at src/engine/strat_engine/tests/loopbacked.rs:116
  13: libstratis::engine::strat_engine::pool::tests::loop_test_add_datadevs
             at src/engine/strat_engine/pool.rs:777
  14: libstratis::engine::strat_engine::pool::tests::loop_test_add_datadevs::{{closure}}
             at src/engine/strat_engine/pool.rs:776
  15: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
  21: test::run_test::run_test_inner
             at src/libtest/lib.rs:1488
  22: test::run_test
             at src/libtest/lib.rs:1507
  23: test::run_tests
             at src/libtest/lib.rs:1166
  24: test::run_tests_console
             at src/libtest/lib.rs:971
  25: test::test_main
             at src/libtest/lib.rs:292
  26: test::test_main_static
             at src/libtest/lib.rs:326
  27: libstratis::main
  28: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  32: std::panicking::try
             at src/libstd/panicking.rs:275
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  35: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  36: main
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 5, kind: Other, message: "Input/output error" })', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12: libstratis::engine::strat_engine::thinpool::thinpool::tests::test_filesystem_snapshot
             at src/engine/strat_engine/thinpool/thinpool.rs:1483
  13: core::ops::function::Fn::call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:69
  14: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec::{{closure}}
             at src/engine/strat_engine/tests/loopbacked.rs:112
  15: std::panicking::try::do_call
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:296
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  17: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  18: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  19: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec
             at src/engine/strat_engine/tests/loopbacked.rs:111
  20: libstratis::engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot
             at src/engine/strat_engine/thinpool/thinpool.rs:1513
  21: libstratis::engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot::{{closure}}
             at src/engine/strat_engine/thinpool/thinpool.rs:1512
  22: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  23: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  25: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  26: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  27: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
  28: test::run_test::run_test_inner
             at src/libtest/lib.rs:1488
  29: test::run_test
             at src/libtest/lib.rs:1507
  30: test::run_tests
             at src/libtest/lib.rs:1166
  31: test::run_tests_console
             at src/libtest/lib.rs:971
  32: test::test_main
             at src/libtest/lib.rs:292
  33: test::test_main_static
             at src/libtest/lib.rs:326
  34: libstratis::main
  35: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  36: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  37: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  38: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  39: std::panicking::try
             at src/libstd/panicking.rs:275
  40: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  41: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  42: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  43: main
  44: __libc_start_main
  45: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::unwrap
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:800
  12: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec
             at src/engine/strat_engine/tests/loopbacked.rs:116
  13: libstratis::engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot
             at src/engine/strat_engine/thinpool/thinpool.rs:1513
  14: libstratis::engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot::{{closure}}
             at src/engine/strat_engine/thinpool/thinpool.rs:1512
  15: core::ops::function::FnOnce::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1466
  21: test::run_test::run_test_inner
             at src/libtest/lib.rs:1488
  22: test::run_test
             at src/libtest/lib.rs:1507
  23: test::run_tests
             at src/libtest/lib.rs:1166
  24: test::run_tests_console
             at src/libtest/lib.rs:971
  25: test::test_main
             at src/libtest/lib.rs:292
  26: test::test_main_static
             at src/libtest/lib.rs:326
  27: libstratis::main
  28: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  32: std::panicking::try
             at src/libstd/panicking.rs:275
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  35: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  36: main
  37: __libc_start_main
  38: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    engine::strat_engine::pool::tests::loop_test_add_datadevs
    engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot

test result: FAILED. 25 passed; 2 failed; 0 ignored; 0 measured; 92 filtered out

error: test failed, to rerun pass '--lib'
make: *** [Makefile:68: test-loop] Error 101
Completed stratisd test (test-loop): status 2
```

**Comment by bgurney-rh** [comment]
If I set up real test devices on the same test system, and run the "test-real" suite in stratisd, there are no failures.

**Comment by bgurney-rh** [comment]
```
test engine::strat_engine::pool::tests::real_test_add_datadevs ... ERROR 2019-10-21T20:41:23Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool out of space! -> OutOfSpace
ERROR 2019-10-21T20:44:53Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool out of space! -> OutOfSpace
ok
```
```
test engine::strat_engine::thinpool::thinpool::tests::real_test_filesystem_snapshot ... ok
```

**Comment by bgurney-rh** [comment]
Interesting result from today: a loop test seemed to complete successfully:

```
test engine::strat_engine::pool::tests::loop_test_add_datadevs ... ERROR 2019-10-25T15:22:35Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool out of space! -> OutOfSpace
ERROR 2019-10-25T15:28:30Z: libstratis::engine::strat_engine::thinpool::thinpool: Thinpool out of space! -> OutOfSpace
ok
```

```
test engine::strat_engine::thinpool::thinpool::tests::loop_test_filesystem_snapshot ... ok
```

**Comment by mulkieran** [comment]
Research issue, pushing to December.

**Comment by bgurney-rh** [comment]
I think I found out why this is happening: the test loop devices are set up in /tmp/(randompath), but the test machines have a tmpfs set up in /tmp, with a total space of about 1 GB.  During these two tests (loop_test_add_datadevs and 

```
Mon 25 Nov 2019 05:27:46 PM EST
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           996M  600M  396M  61% /tmp
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                 DIO LOG-SEC
/dev/loop1         0      0         0  0 /tmp/stratisCPnJlg/store1   0     512
/dev/loop0         0      0         0  0 /tmp/stratisCPnJlg/store0   0     512
```

Eventually, the space in /tmp fills to capacity, meaning it's not possible to use the other loop device, due to (I'm guessing) EIO.

```
Mon 25 Nov 2019 05:28:47 PM EST
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           996M  996M     0 100% /tmp
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                 DIO LOG-SEC
/dev/loop1         0      0         0  0 /tmp/stratisYPC566/store1   0     512
/dev/loop0         0      0         0  0 /tmp/stratisYPC566/store0   0     512
```

**Comment by bgurney-rh** [comment]
The default size for a tmpfs is 50% of the physical memory size on the system, therefore that explains the 1 GB /tmp on my test VM with 2 GB of RAM.

**Comment by mulkieran** [comment]
The purpose is to show that adding blockdevs allows the pool to be extended. add_blockdevs is called, and then various health indicators of the pool are checked.

```
---- engine::strat_engine::pool::tests::loop_test_add_datadevs stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 5, kind: Other, message: "Input/output error" })', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12: libstratis::engine::strat_engine::pool::tests::test_add_datadevs
             at src/engine/strat_engine/pool.rs:761
  13: core::ops::function::Fn::call
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:69
  14: libstratis::engine::strat_engine::tests::loopbacked::test_with_spec::{{closure}}
             at src/engine/strat_engine/tests/loopbacked.rs:112
```

pool.rs: 761 is the very last step in the test_add_datadevs

```
            pool.add_blockdevs(pool_uuid, name, paths2, BlockDevTier::Data)
                .unwrap();
```

Looks like we are failing either when adding the datadevs or in subsequent check() of pool or when writing the new metadata. That gives us plenty of options, the question is which would give that kind of io error?

When we add the datadevs, we write their initial metadata.
When we extend the pool, we simply issue instructions to dm, so that's not the candidate.
Then, when we unconditionally rewrite the metadata, that's more writing.

Let's keep this open...but don't feel the need to keep the test system the way it is.

**Comment by mulkieran** [comment]
backgrounding this.

**Comment by mulkieran** [comment]
I think we can call this obsolete.
