### ISSUE TITLE
Unable to build stratisd - failed to run custom build command for `libdbus-sys v0.1.5`

### ISSUE THREAD

**Issue by kamathe** [stratis-storage/stratisd#1827]
Trying to build stratisd using cargo build, however it is giving following error

failed to run custom build command for `libdbus-sys v0.1.5`

Complete build logs

```
[root@testbox stratisd]# RUST_BACKTRACE=full cargo build
   Compiling libc v0.2.66
   Compiling cc v1.0.50
   Compiling cfg-if v0.1.2
   Compiling version_check v0.1.5
   Compiling autocfg v0.1.6
   Compiling bitflags v1.2.1
   Compiling rand_core v0.4.2
   Compiling ucd-util v0.1.1
   Compiling lazy_static v1.4.0
   Compiling regex v1.0.3
   Compiling quick-error v1.2.2
   Compiling glob v0.3.0
   Compiling utf8-ranges v1.0.0
   Compiling pkg-config v0.3.9
   Compiling proc-macro2 v1.0.8
   Compiling unicode-width v0.1.4
   Compiling unicode-xid v0.2.0
   Compiling strsim v0.6.0
   Compiling vec_map v0.8.0
   Compiling ansi_term v0.10.2
   Compiling bindgen v0.51.1
   Compiling termcolor v1.1.0
   Compiling serde v1.0.82
   Compiling peeking_take_while v0.1.2
   Compiling shlex v0.1.1
   Compiling rustc-hash v1.1.0
   Compiling nix v0.14.0
   Compiling unicode-xid v0.0.4
   Compiling num-traits v0.2.5
   Compiling void v1.0.2
   Compiling rustc-demangle v0.1.5
   Compiling quote v0.3.15
   Compiling num-integer v0.1.39
   Compiling either v1.5.3
   Compiling dtoa v0.4.1
   Compiling itoa v0.3.1
   Compiling num-traits v0.1.37
   Compiling lazy_static v0.2.8
   Compiling remove_dir_all v0.5.1
   Compiling termcolor v0.3.6
   Compiling byteorder v1.2.7
   Compiling log v0.4.2
   Compiling nom v4.2.3
   Compiling error-chain v0.12.1
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling libloading v0.5.2
   Compiling backtrace-sys v0.1.16
   Compiling regex-syntax v0.6.1
   Compiling thread_local v0.3.6
   Compiling humantime v1.1.1
   Compiling clang-sys v0.28.1
   Compiling libdbus-sys v0.1.5
   Compiling libudev-sys v0.1.3
   Compiling textwrap v0.9.0
   Compiling synom v0.11.3
   Compiling itertools v0.8.0
   Compiling crc v1.4.0
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
error: failed to run custom build command for `libdbus-sys v0.1.5`

Caused by:
  process didn't exit successfully: `/root/stratisd/target/debug/build/libdbus-sys-89c4e75ea7d1d4bc/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x558d5abe3024 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x558d5abe3024 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x558d5abe3024 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x558d5abe3024 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x558d5ac0100c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x558d5abe0677 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x558d5abe514e - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x558d5abe514e - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x558d5abe514e - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x558d5abe4e41 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x558d5abe577b - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x558d5abe532e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x558d5abfe6be - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x558d5abfe7b7 - core::result::unwrap_failed::hca6a012bfa3eb903
                               at src/libcore/result.rs:1188
  14:     0x558d5abbacf5 - core::result::Result<T,E>::unwrap::h1926c8493bcb1471
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:956
  15:     0x558d5abba47d - build_script_build::main::h00e6dd1cee0da6d7
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.1.5/build.rs:6
  16:     0x558d5abbadd0 - std::rt::lang_start::{{closure}}::h36c382b391cf5f56
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  17:     0x558d5abe5213 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7
                               at src/libstd/rt.rs:52
  18:     0x558d5abe5213 - std::panicking::try::do_call::hccaa7cebf2335ab2
                               at src/libstd/panicking.rs:292
  19:     0x558d5abebc5a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:     0x558d5abe5c10 - std::panicking::try::h3ce8e2e4440720f0
                               at src/libstd/panicking.rs:270
  21:     0x558d5abe5c10 - std::panic::catch_unwind::h2a767bac361346af
                               at src/libstd/panic.rs:394
  22:     0x558d5abe5c10 - std::rt::lang_start_internal::h14e7168ba039f170
                               at src/libstd/rt.rs:51
  23:     0x558d5abbada9 - std::rt::lang_start::hb5ac57ccc7899298
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  24:     0x558d5abba4ea - main
  25:     0x7f13aeb3a495 - __libc_start_main
  26:     0x558d5abba2f9 - <unknown>
  27:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
[root@testbox stratisd]# 
```

Setup details

```
[root@testbox stratisd]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[root@testbox stratisd]# 
[root@testbox stratisd]# uname -r
3.10.0-957.el7.x86_64
[root@testbox stratisd]# 
[root@testbox stratisd]# rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
[root@testbox stratisd]# 
[root@testbox stratisd]# cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
[root@testbox stratisd]# 
```

Results on a RHEL8 machine

```
[root@testbox2 stratisd (develop-2.0.1)]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ uname -r
4.18.0-147.el8.x86_64
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

Build logs

```
[root@testbox2 stratisd (develop-2.0.1)]$ RUST_BACKTRACE=full cargo build
   Compiling libloading v0.5.2
   Compiling backtrace-sys v0.1.16
   Compiling clang-sys v0.28.1
   Compiling libdbus-sys v0.1.5
   Compiling libudev-sys v0.1.3
   Compiling memchr v2.0.1
   Compiling memchr v1.0.1
   Compiling atty v0.2.6
   Compiling which v3.1.0
   Compiling quote v1.0.2
   Compiling rand_os v0.1.3
   Compiling nix v0.14.0
   Compiling serde_json v1.0.2
   Compiling rand v0.4.3
   Compiling time v0.1.37
   Compiling timerfd v1.0.0
   Compiling bindgen v0.51.1
   Compiling num-integer v0.1.39
error: failed to run custom build command for `libudev-sys v0.1.3`

Caused by:
  process didn't exit successfully: `/root/stratisd/target/debug/build/libudev-sys-72e8dec413b7eab5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'libudev\', required by \'virtual:world\', not found\n"', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x559fba4d8a84 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x559fba4d8a84 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x559fba4d8a84 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x559fba4d8a84 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x559fba4f6b4c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x559fba4d5bf7 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x559fba4dabae - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x559fba4dabae - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x559fba4dabae - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x559fba4da8a1 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x559fba4db1db - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x559fba4dad8e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x559fba4f41fe - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x559fba4f42f7 - core::result::unwrap_failed::hca6a012bfa3eb903
                               at src/libcore/result.rs:1188
  14:     0x559fba4ae72e - core::result::Result<T,E>::unwrap::he246da750da888d1
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:956
  15:     0x559fba4ac326 - build_script_build::main::hf933c3baad54e939
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.3/build.rs:39
  16:     0x559fba4aeba0 - std::rt::lang_start::{{closure}}::hd0b67c9b491b4996
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  17:     0x559fba4dac73 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7
                               at src/libstd/rt.rs:52
  18:     0x559fba4dac73 - std::panicking::try::do_call::hccaa7cebf2335ab2
                               at src/libstd/panicking.rs:292
  19:     0x559fba4e179a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:     0x559fba4db670 - std::panicking::try::h3ce8e2e4440720f0
                               at src/libstd/panicking.rs:270
  21:     0x559fba4db670 - std::panic::catch_unwind::h2a767bac361346af
                               at src/libstd/panic.rs:394
  22:     0x559fba4db670 - std::rt::lang_start_internal::h14e7168ba039f170
                               at src/libstd/rt.rs:51
  23:     0x559fba4aeb79 - std::rt::lang_start::h1342d9513256ff1e
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  24:     0x559fba4ac42a - main
  25:     0x14dfb00c2873 - __libc_start_main
  26:     0x559fba4abade - _start
  27:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `libdbus-sys v0.1.5`

Caused by:
  process didn't exit successfully: `/root/stratisd/target/debug/build/libdbus-sys-89c4e75ea7d1d4bc/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'dbus-1\', required by \'virtual:world\', not found\n" } }', src/libcore/result.rs:1188:5
stack backtrace:
   0:     0x5594da2b6294 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5594da2b6294 - backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5594da2b6294 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x5594da2b6294 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfe37fa5de6572965
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5594da2d427c - core::fmt::write::h74887d18db27282c
                               at src/libcore/fmt/mod.rs:1025
   5:     0x5594da2b38e7 - std::io::Write::write_fmt::h6808f3d5eceed5e5
                               at src/libstd/io/mod.rs:1426
   6:     0x5594da2b83be - std::sys_common::backtrace::_print::hcc0fd4b3552039ef
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5594da2b83be - std::sys_common::backtrace::print::h1c9c5c1c0505592d
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5594da2b83be - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59
                               at src/libstd/panicking.rs:193
   9:     0x5594da2b80b1 - std::panicking::default_hook::h1b037d2bf0657ab3
                               at src/libstd/panicking.rs:210
  10:     0x5594da2b89eb - std::panicking::rust_panic_with_hook::h787d7f532b084b9a
                               at src/libstd/panicking.rs:471
  11:     0x5594da2b859e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x5594da2d192e - core::panicking::panic_fmt::h76b979c035808e69
                               at src/libcore/panicking.rs:84
  13:     0x5594da2d1a27 - core::result::unwrap_failed::hca6a012bfa3eb903
                               at src/libcore/result.rs:1188
  14:     0x5594da28df65 - core::result::Result<T,E>::unwrap::h1926c8493bcb1471
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:956
  15:     0x5594da28d6ed - build_script_build::main::h00e6dd1cee0da6d7
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libdbus-sys-0.1.5/build.rs:6
  16:     0x5594da28e040 - std::rt::lang_start::{{closure}}::h36c382b391cf5f56
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  17:     0x5594da2b8483 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7
                               at src/libstd/rt.rs:52
  18:     0x5594da2b8483 - std::panicking::try::do_call::hccaa7cebf2335ab2
                               at src/libstd/panicking.rs:292
  19:     0x5594da2beeca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  20:     0x5594da2b8e80 - std::panicking::try::h3ce8e2e4440720f0
                               at src/libstd/panicking.rs:270
  21:     0x5594da2b8e80 - std::panic::catch_unwind::h2a767bac361346af
                               at src/libstd/panic.rs:394
  22:     0x5594da2b8e80 - std::rt::lang_start_internal::h14e7168ba039f170
                               at src/libstd/rt.rs:51
  23:     0x5594da28e019 - std::rt::lang_start::hb5ac57ccc7899298
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67
  24:     0x5594da28d75a - main
  25:     0x14561107e873 - __libc_start_main
  26:     0x5594da28d59e - _start
  27:                0x0 - <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

It seems that a pkg-config command is failing, tried running that manually

```
[root@testbox2 stratisd (develop-2.0.1)]$ pkg-config --libs --cflags dbus-1 >= 1.6
Package dbus-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `dbus-1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dbus-1', required by 'virtual:world', not found
Package '1.6', required by 'virtual:world', not found
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

However the dbus-1 package is installed

```
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qa | grep -i dbus-1
dbus-1.12.8-9.el8.x86_64
python3-dbus-1.2.4-15.el8.x86_64
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qi dbus-1.12.8-9.el8.x86_64
Name        : dbus
Epoch       : 1
Version     : 1.12.8
Release     : 9.el8
Architecture: x86_64
Install Date: Wed 19 Feb 2020 04:16:05 AM EST
Group       : System Environment/Libraries
Size        : 0
License     : (GPLv2+ or AFL) and GPLv2+
Signature   : RSA/SHA256, Thu 01 Aug 2019 05:00:50 AM EDT, Key ID 199e2f91fd431d51
Source RPM  : dbus-1.12.8-9.el8.src.rpm
Build Date  : Thu 01 Aug 2019 02:25:11 AM EDT
Build Host  : x86-vm-05.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : http://www.freedesktop.org/Software/dbus/
Summary     : D-BUS message bus
Description :
D-BUS is a system for sending messages between applications. It is
used both for the system-wide message bus service, and as a
per-user-login-session messaging facility.
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

**Comment by jbaublitz** [comment]
Hi @kamathe. Do you have `dbus-devel` (or potentially `dbus-1-devel` - it is `dbus-devel` on Fedora) installed? Stratis requires the appropriate `-devel` packages to be installed for the files that are used to build against the actual non-devel packages.

**Comment by kamathe** [comment]
@jbaublitz Installed it and tried again, did not work, logs below


Installed dbus-devel

```
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qa | grep -i dbus-devel
dbus-devel-1.12.8-9.el8.x86_64
[root@testbox2 stratisd (develop-2.0.1)]$ 
```
Firing cargo build which failed again

```
[root@testbox2 stratisd (develop-2.0.1)]$ cargo build
   Compiling libloading v0.5.2
   Compiling backtrace-sys v0.1.16
   Compiling libudev-sys v0.1.3
   Compiling bindgen v0.51.1
   Compiling timerfd v1.0.0
   Compiling aho-corasick v0.6.3
   Compiling nom v4.2.3
   Compiling clap v2.29.0
   Compiling num-integer v0.1.39
   Compiling libdbus-sys v0.1.5
error: failed to run custom build command for `libudev-sys v0.1.3`

Caused by:
  process didn't exit successfully: `/root/stratisd/target/debug/build/libudev-sys-72e8dec413b7eab5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'libudev\', required by \'virtual:world\', not found\n"', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

Tried it manually

```
[root@testbox2 stratisd (develop-2.0.1)]$ /root/stratisd/target/debug/build/libudev-sys-72e8dec413b7eab5/build-script-build
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'libudev\', required by \'virtual:world\', not found\n"', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[root@rdma-dev-25 stratisd (develop-2.0.1)]$ 
[root@rdma-dev-25 stratisd (develop-2.0.1)]$ 
[root@rdma-dev-25 stratisd (develop-2.0.1)]$ pkg-config --libs --cflags libudev
Package libudev was not found in the pkg-config search path.
Perhaps you should add the directory containing `libudev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libudev', required by 'virtual:world', not found
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

**Comment by mulkieran** [comment]
@kamathe You might find this useful: https://github.com/stratis-storage/project/issues/143. I just did a fresh build of stratisd on Fedora 30, and I listed out all the dependencies I had to explicitly install: "clang, libudev-devel, dbus-devel, cryptsetup-devel".

**Comment by mulkieran** [comment]
@kamathe Please re-open if you continue to have problems after installing the dependencies listed.

**Comment by kamathe** [comment]
@mulkieran I am still having trouble building it, i installed most of the packages that you mentioned, however i am having a hard time finding ```libudev```, i see ```libgudev``` in most repos on RHEL7, 8 and Fedora 30

Please suggest alternatives to get the ```libudev``` package

Listing of packages that are required to be pre-installed before building stratisd

```
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qa | grep -Ei '^clang|libudev|dbus-devel|cryptsetup-devel'
dbus-devel-1.12.8-9.el8.x86_64
clang-8.0.1-1.module+el8.1.0+3866+6be7f4d8.x86_64
cryptsetup-devel-2.2.0-2.el8.x86_64
clang-libs-8.0.1-1.module+el8.1.0+3866+6be7f4d8.x86_64
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

Installed ```libgudev``` since ```libudev``` is not available in any of the repos

```
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qa | grep -i libudev
[root@testbox2 stratisd (develop-2.0.1)]$ 
[root@testbox2 stratisd (develop-2.0.1)]$ rpm -qa | grep -i libgudev
libgudev-232-4.el8.x86_64
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

Build failing again due to same error

```
[root@testbox2 stratisd (develop-2.0.1)]$ cargo build
   Compiling libudev-sys v0.1.3
   Compiling clang-sys v0.28.1
   Compiling backtrace v0.3.3
   Compiling serde_derive v1.0.8
   Compiling chrono v0.4.5
   Compiling env_logger v0.6.2
   Compiling uuid v0.7.4
   Compiling env_logger v0.5.10
error: failed to run custom build command for `libudev-sys v0.1.3`

Caused by:
  process didn't exit successfully: `/root/stratisd/target/debug/build/libudev-sys-72e8dec413b7eab5/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit code: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'libudev\', required by \'virtual:world\', not found\n"', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
[root@testbox2 stratisd (develop-2.0.1)]$ 
```

**Comment by kamathe** [comment]
@mulkieran 

I was able to install stratis using the pre-build packages from the repo, instead of trying to build it by hand

```
[root@testbox2 ~]$ rpm -qa |grep -i stratis
stratisd-1.0.4-2.el8.x86_64
stratis-cli-1.0.4-2.el8.noarch
[root@testbox2 ~]$
[root@testbox2 ~]$ stratis --version
2.0.1
[root@testbox2 ~]$ 

```


I started the stratisd service via systemctl
 
```
[root@testbox2 ~]$ ps aux | grep -i stratis
root     18902  0.0  0.0  51112  6088 ?        Ss   01:53   0:00 /usr/libexec/stratisd --debug
root     20011  0.0  0.0  12112   984 pts/0    S+   01:59   0:00 /bin/grep --color=tty -i stratis
[root@testbox2 ~]$ 
```

However when i run stratis-cli, it errors out saying can't connect to D-Bus service
Is it related to the same package ```libudev``` not being present ?

```
[root@testbox2 ~]$ stratis pool list
Execution failed:
Most likely stratis is unable to connect to the stratisd D-Bus service. 
[root@testbox2 ~]$ 
```

How do i go about debugging stratis when some issue occurs, this will help me provide additional debugging information in the bug

**Comment by mulkieran** [comment]
@kamathe Probably by installing stratisd by hand you missed out on an essential step for setting up the D-Bus service. See these instructions here: https://github.com/stratis-storage/stratisd#configuring. If you had also installed stratisd from the repo, instead of from the source, that part would have been handled for you by the package spec.
