### ISSUE TITLE
Python-based udev test errors should be investigated

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd#2719]
Error: https://github.com/stratis-storage/stratisd/pull/2717/checks?check_run_id=3116308497

```
2021-07-20T17:26:17.6152204Z Create more than one pool with the same name, then dynamically fix it ... ERROR
2021-07-20T17:26:17.6192769Z /usr/lib64/python3.9/subprocess.py:1052: ResourceWarning: subprocess 10747 is still running
2021-07-20T17:26:17.6194530Z   _warn("subprocess %s is still running" % self.pid,
2021-07-20T17:26:17.6195674Z ResourceWarning: Enable tracemalloc to get the object allocation traceback
2021-07-20T17:26:17.6199527Z /usr/lib64/python3.9/unittest/case.py:621: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
2021-07-20T17:26:17.6212649Z   outcome.errors.clear()
2021-07-20T17:26:17.6215263Z ResourceWarning: Enable tracemalloc to get the object allocation traceback
2021-07-20T17:26:17.6217261Z /usr/lib64/python3.9/unittest/case.py:621: ResourceWarning: unclosed file <_io.TextIOWrapper name=6 encoding='UTF-8'>
2021-07-20T17:26:17.6218236Z   outcome.errors.clear()
2021-07-20T17:26:17.6219063Z ResourceWarning: Enable tracemalloc to get the object allocation traceback
2021-07-20T17:26:17.6219630Z 
2021-07-20T17:26:17.6220141Z ======================================================================
2021-07-20T17:26:17.6220959Z ERROR: test_duplicate_pool_name (tests.udev.test_udev.UdevTest5)
2021-07-20T17:26:17.6221755Z Create more than one pool with the same name, then dynamically fix it
2021-07-20T17:26:17.6222658Z ----------------------------------------------------------------------
2021-07-20T17:26:17.6223251Z Traceback (most recent call last):
2021-07-20T17:26:17.6224198Z   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
2021-07-20T17:26:17.6225028Z     return dbus_method(*xformed_args, timeout=timeout)
2021-07-20T17:26:17.6225997Z   File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
2021-07-20T17:26:17.6226820Z     return self._connection.call_blocking(self._named_service,
2021-07-20T17:26:17.6227862Z   File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
2021-07-20T17:26:17.6228684Z     reply_message = self.send_message_with_reply_and_block(
2021-07-20T17:26:17.6230690Z dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2021-07-20T17:26:17.6232387Z 
2021-07-20T17:26:17.6232928Z The above exception was the direct cause of the following exception:
2021-07-20T17:26:17.6233387Z 
2021-07-20T17:26:17.6233971Z Traceback (most recent call last):
2021-07-20T17:26:17.6235035Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/test_udev.py", line 555, in test_duplicate_pool_name
2021-07-20T17:26:17.6236276Z     self.wait_for_pools(len(current_pools) + 1)
2021-07-20T17:26:17.6237204Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/_utils.py", line 460, in wait_for_pools
2021-07-20T17:26:17.6237926Z     known_pools = get_pools(name=name)
2021-07-20T17:26:17.6238984Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/_utils.py", line 108, in get_pools
2021-07-20T17:26:17.6240137Z     managed_objects = ObjectManager.Methods.GetManagedObjects(
2021-07-20T17:26:17.6241713Z   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 325, in dbus_func
2021-07-20T17:26:17.6242726Z     raise DPClientInvocationError(err_msg, interface_name,
2021-07-20T17:26:17.6244660Z dbus_python_client_gen._errors.DPClientInvocationError: Error while invoking method "GetManagedObjects" belonging to interface "org.freedesktop.DBus.ObjectManager" with arguments ()
2021-07-20T17:26:17.6247187Z 
2021-07-20T17:26:17.6248114Z During handling of the above exception, another exception occurred:
2021-07-20T17:26:17.6248588Z 
2021-07-20T17:26:17.6248980Z Traceback (most recent call last):
2021-07-20T17:26:17.6250222Z   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
2021-07-20T17:26:17.6251074Z     return dbus_method(*xformed_args, timeout=timeout)
2021-07-20T17:26:17.6252027Z   File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
2021-07-20T17:26:17.6253026Z     return self._connection.call_blocking(self._named_service,
2021-07-20T17:26:17.6254052Z   File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
2021-07-20T17:26:17.6254872Z     reply_message = self.send_message_with_reply_and_block(
2021-07-20T17:26:17.6256684Z dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
2021-07-20T17:26:17.6258378Z 
2021-07-20T17:26:17.6258934Z The above exception was the direct cause of the following exception:
2021-07-20T17:26:17.6259396Z 
2021-07-20T17:26:17.6259787Z Traceback (most recent call last):
2021-07-20T17:26:17.6261066Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/test_udev.py", line 557, in test_duplicate_pool_name
2021-07-20T17:26:17.6261850Z     self.wait_for_pools(num_pools)
2021-07-20T17:26:17.6262767Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/_utils.py", line 419, in __exit__
2021-07-20T17:26:17.6263511Z     self._keys.__exit__(exc_type, exc_val, exc_tb)
2021-07-20T17:26:17.6264462Z   File "/__w/stratisd/stratisd/tests/client-dbus/tests/udev/_utils.py", line 356, in __exit__
2021-07-20T17:26:17.6265367Z     (_, return_code, message) = Manager.Methods.UnsetKey(
2021-07-20T17:26:17.6266681Z   File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 325, in dbus_func
2021-07-20T17:26:17.6267623Z     raise DPClientInvocationError(err_msg, interface_name,
2021-07-20T17:26:17.6269140Z dbus_python_client_gen._errors.DPClientInvocationError: Error while invoking method "UnsetKey" belonging to interface "org.storage.stratis3.Manager.r0" with arguments (key_desc_3)
```

The tracebacks indicate that stratisd is not responding to D-Bus messages, this may be caused by the synthetic udev events that are caused just before the first traceback. We should first verify that stratisd has not simply gone down at this point, though. The first traceback is the original problem, the second is where the enclosing context tries to clean up a key.

**Comment by mulkieran** [comment]
Reopening...identical error has now been observed at least once on Fedora 34 since we moved up.

**Comment by mulkieran** [comment]
I think the secret may be that GetManagedObjects is being called twice in succession w/out any intervening operation.

**Comment by mulkieran** [comment]
We are not seeing these any more, closing in favor of #2825
