### ISSUE TITLE
The following error occurred on the hm-smr hard disk

### ISSUE THREAD

**Issue by twosson** [stratis-storage/stratisd#2876]
[root@fedora ~]# stratis --propagate fs list
Pool Name   Name    Size                        Created             Device                    UUID
chia        demo2   1 TiB / FAILURE / FAILURE   Dec 14 2021 21:06   /dev/stratis/chia/demo2   c5d9792f-b700-4fd7-85e5-1c00558365e2
chia        demo3   1 TiB / FAILURE / FAILURE   Dec 14 2021 21:06   /dev/stratis/chia/demo3   7593ddcf-3458-407a-80ec-8d6c95bd2262
[root@fedora ~]# stratis --propagate fs destroy chia demo2
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/stratis_cli/_main.py", line 43, in the_func
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/stratis_cli/_parser/_parser.py", line 89, in wrapped_func
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/stratis_cli/_actions/_logical.py", line 230, in destroy_volumes
stratis_cli._errors.StratisCliEngineError: ERROR: low-level ioctl error due to nix error; header result: Some(DeviceInfo { version: Version { major: 4, minor: 45, patch: 0 }, data_size: 16384, data_start: 312, target_count: 0, open_count: 0, flags: (empty), event_nr: 0, dev: Device { major: 0, minor: 0 }, name: Some(DmNameBuf { inner: "stratis-1-100d2029879f4d60b5cecbe7f5b9a128-thin-fs-c5d9792fb7004fd785e51c00558365e2" }), uuid: None }), error: ENXIO: No such device or address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/stratis", line 4, in <module>
    __import__('pkg_resources').run_script('stratis-cli==3.0.0', 'stratis')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/EGG-INFO/scripts/stratis", line 35, in <module>
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/EGG-INFO/scripts/stratis", line 32, in main
  File "/usr/local/lib/python3.10/site-packages/stratis_cli-3.0.0-py3.10.egg/stratis_cli/_main.py", line 59, in the_func
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['--propagate', 'fs', 'destroy', 'chia', 'demo2'] which were parsed to Namespace(propagate=True, unhyphenated_uuids=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7f0b49e763b0>, pool_name='chia', fs_name=['demo2']) failed

**Comment by bgurney-rh** [comment]
Hi,

Can you please provide the version of Fedora being used, and the kernel version (`uname -r`)?

Also, for the block device being used in the pool, can you run `cat /sys/block/<device>/queue/zoned`?

**Comment by bgurney-rh** [comment]
The above information will confirm what I think is happening, but when you say "hm-smr hard disk", I'm assuming you mean "host-managed shingled magnetic recording hard disk".  If that is the case, Stratis uses device-mapper thin provisioning (dm-thin), which does not support zoned block devices.

**Comment by mulkieran** [comment]
Migrating to project
