### ISSUE TITLE
CLI timeouts

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratisd#617]
running the CLI to create a single filesystem on our Open Stack VM times out

**Comment by mulkieran** [comment]
Can you give more specifics?

**Comment by mulkieran** [comment]
```
[root@host-172-16-191-11 ~]# stratis filesystem create pool fs2
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus_python_client_gen-0.4-py3.6.egg/dbus_python_client_gen/_invokers.py", line 289, in dbus_func
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 4, in <module>
    __import__('pkg_resources').run_script('stratis-cli==0.0.3', 'stratis')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1507, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/stratis_cli-0.0.3-py3.6.egg/EGG-INFO/scripts/stratis", line 32, in <module>
  File "/usr/lib/python3.6/site-packages/stratis_cli-0.0.3-py3.6.egg/EGG-INFO/scripts/stratis", line 29, in main
  File "/usr/lib/python3.6/site-packages/stratis_cli-0.0.3-py3.6.egg/stratis_cli/_main.py", line 37, in the_func
  File "/usr/lib/python3.6/site-packages/stratis_cli-0.0.3-py3.6.egg/stratis_cli/_actions/_logical.py", line 56, in create_volumes
  File "/usr/lib/python3.6/site-packages/dbus_python_client_gen-0.4-py3.6.egg/dbus_python_client_gen/_invokers.py", line 291, in dbus_func
dbus_python_client_gen._errors.DPClientRuntimeError

```

**Comment by mulkieran** [comment]
According to the code, an infinite timeout is not an option. We are accepting the "sane" default chosen by libdbus.

**Comment by mulkieran** [comment]
```dbus-python-client-gen``` was updated to allow setting timeout ability, so we can do that as necessary.

**Comment by tasleson** [comment]
With the merge of https://github.com/stratis-storage/stratis-cli/pull/160 this issue should mostly mitigated.
